<article>
                    <img class="mainIMG" src="[field:litpic/]" alt="Main Blog Image" />
                    <h2>[field:title/]</h2>
                    <div class="article-wrapper">
                        <span class="date-info">[field:pubdate function="GetDateTimeMK(@me)"/] </span>
                        <span class="comment-info">[field:scores/]  Comments</span>
                        <p>
                            [field:description/]...
                        </p>
                        <hr />
                        <a href="[field:arcurl/]">Read more »</a>
                    </div>
                </article>