<article>
                    <img class="mainIMG" src="[field:litpic/]" alt="Main Blog Image" />
                    <h2>[field:title/]</h2>
                    <div class="article-wrapper">
                        <span class="date-info">January 23, 2012</span>
                        <span class="comment-info">3 Comments</span>
                        <p>
                           [field:description/]...
                        </p>
                        <hr />
                        <a href="[field:arcurl/]" target="_blank">Read more »</a>
                    </div>
                </article>