<?php
$z[0]=Array("arcurl","",41,56);
$z[1]=Array("title","",74,88);
$z[2]=Array("pubdate","  \r\n\$a=\"<font color='#ff0000'>\";  \r\n\$d=\"<font color='#858585'>\";  \r\n\$b=\"</font>\";  \r\n\$c=strftime(\"%m-%d\",\"@me\");  \r\n\$ntime = time();  \r\n\$oneday = 3600 * 24;  \r\nif((\$ntime - @me)<\$oneday) @me = \$a.\$c.\$b;  \r\nelse @me = \$d.\$c.\$b;  \r\n",139,413);
$z[2][4]['runphp']="yes";

?>