<?php
$z[0]=Array("global","",444,476);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",549,581);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",835,867);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",936,968);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",1174,1209);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1589,1608);
$z[5][4]['name']="title";
$z[6]=Array("field","",1712,1768);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[7]=Array("field","",1827,1847);
$z[7][4]['name']="writer";
$z[8]=Array("field","",1919,1937);
$z[8][4]['name']="body";
$z[9]=Array("include","",4847,4884);
$z[9][4]['filename']="footer.htm";

?>