<?php
$z[0]=Array("global","",444,476);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",549,581);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",835,867);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",936,968);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",1160,1195);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","\n                  <img src='[field:imgsrc/]' id='bigimg' [field:imgwidth /] alt='[field:alttext /]'  class=\"mainIMG\"  />\n             ",1473,1670);
$z[5][4]['name']="imgurls";
$z[5][4]['alt']="图片输出区";
$z[6]=Array("field","",1737,1756);
$z[6][4]['name']="title";
$z[7]=Array("field","",1788,1844);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[8]=Array("field","",1957,1975);
$z[8][4]['name']="body";
$z[9]=Array("prenext","",2835,2860);
$z[9][4]['get']="pre";
$z[10]=Array("include","",3052,3089);
$z[10][4]['filename']="footer.htm";

?>