{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52636.jpg' text='原创风景图片' width='' height=''} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52636.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52637.jpg' text='原创风景图片' width='' height=''} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52637.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52638.jpg' text='原创风景图片' width='' height=''} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52638.jpg {/dede:img}
{dede:img ddimg='http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52639.jpg' text='原创风景图片' width='' height=''} http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52639.jpg {/dede:img}
