<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52636.jpg ",93,310);
$z[1][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52636.jpg";
$z[1][4]['text']="原创风景图片";
$z[1][4]['width']="";
$z[1][4]['height']="";
$z[2]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52637.jpg ",312,529);
$z[2][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52637.jpg";
$z[2][4]['text']="原创风景图片";
$z[2][4]['width']="";
$z[2][4]['height']="";
$z[3]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52638.jpg ",531,748);
$z[3][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52638.jpg";
$z[3][4]['text']="原创风景图片";
$z[3][4]['width']="";
$z[3][4]['height']="";
$z[4]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52639.jpg ",750,967);
$z[4][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G52639.jpg";
$z[4][4]['text']="原创风景图片";
$z[4][4]['width']="";
$z[4][4]['height']="";

?>