<div class="coin-widget fl">
                <div class="cl">
                  <p class="shadow-l"></p>
                  <a target="_blank" href="[field:arcurl/]" class="coin-pp"><img alt="[field:fulltitle/]" src="[field:litpic/]" /><span></span><em>[field:title/]</em></a>
                  <p class="shadow-r"></p>
                </div>
                <div class="coin-price"><a rel="nofollow" target="_blank" href="[field:arcurl/]" class="orange-btn">Á¢¼´ÇÀ¹º</a></div>
              </div>