<?php
$z[0]=Array("global","",200,225);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channel","\r\n                   \r\n                     <div class=\"ui-block-b\"><a href='[field:typeurl/]' [field:rel/] data-transition=\"flip\"> [field:typename/]</a></div>\r\n                     \r\n                     ",309,650);
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['currentstyle']="<div class='ui-block-b'><a href='~typelink~' ~rel~>~typename~</a></div>";

?>