<?php
$z[0]=Array("global","",448,480);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",557,589);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",843,875);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",944,976);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",1168,1203);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist","   \n                <article>\n                    <a href=\"[field:arcurl/]\">\n                        <img class=\"mainIMG\" src=\"[field:litpic/]\" alt=\"[field:title function='html2text(@me)'/]\" />\n                        <h2>[field:title/]</h2>\n                        <span>[field:pubdate function=\"GetDateMK(@me)\"/]</span>\n                    </a>\n                </article>\n                ",1427,1882);
$z[5][4]['row']="5";
$z[5][4]['type']="image.";
$z[5][4]['orderby']="click";
$z[6]=Array("global","",2080,2112);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",2453,2485);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("include","",3082,3119);
$z[8][4]['filename']="footer.htm";

?>